# Generated by Django 4.1.7 on 2023-02-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ITS', '0004_alter_issues_assignee_us_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='project_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ITS.project'),
        ),
    ]
