# Generated by Django 4.1.7 on 2023-02-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITS', '0006_alter_contributors_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='permission',
            field=models.CharField(choices=[('USER', 'USER'), ('SUPERUSER', 'SUPERUSER')], max_length=20),
        ),
    ]
