# Generated by Django 4.1.7 on 2023-02-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ITS', '0008_alter_contributors_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ITS.project'),
        ),
    ]
