# Generated by Django 4.1.7 on 2023-02-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITS', '0011_alter_contributors_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author_user_id',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='issue_id',
            new_name='issue',
        ),
        migrations.RenameField(
            model_name='contributors',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='contributors',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='assignee_us_id',
            new_name='assignee_us',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='author_user_id',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='author_user_id',
            new_name='author_user',
        ),
    ]
