# Generated by Django 4.1.7 on 2023-02-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITS', '0012_rename_author_user_id_comments_author_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='issue',
            new_name='issues',
        ),
    ]
