# Generated by Django 3.2.5 on 2023-03-07 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITS', '0016_alter_comment_issue_alter_contributor_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='assignee_us',
            new_name='assignee_user',
        ),
    ]
