# Generated by Django 4.1.7 on 2023-04-12 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ITS', '0017_rename_assignee_us_issue_assignee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('CO', 'Contributor'), ('PO', 'Project Owner')], default='CO', max_length=20),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='ITS.project'),
        ),
    ]
