# Generated by Django 4.1.7 on 2023-04-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITS', '0018_alter_contributor_permission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='user',
            new_name='author_user',
        ),
    ]
