# Generated by Django 4.1.7 on 2023-04-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITS', '0019_rename_user_contributor_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='author_user',
            new_name='user',
        ),
    ]
