# Generated by Django 4.1.7 on 2023-04-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITS', '0020_rename_author_user_contributor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('Contributor', 'Contributor'), ('Project Owner', 'Project Owner')], default='Contributor', max_length=20),
        ),
    ]
